name: Dependabot `prek auto-update`

on:
  push:
    branches:
      - "dependabot/github_actions/**"

jobs:
  prek-auto-update:
    # Only run on dependabot PRs
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PUSH_TOKEN }}
      - uses: taiki-e/install-action@v2
        with:
          tool: prek
      - run: prek auto-update

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m $'`prek auto-update`\n\n[dependabot skip]'
            git push
          fi
